apiVersion: v1
kind: ConfigMap
metadata:
  name: git-mcp-config
  namespace: ${namespace}
data:
  GIT_GITHUB_API_URL: ${github_api_url}
  GIT_GITLAB_API_URL: ${gitlab_api_url}
  GIT_GITEA_API_URL: ${gitea_api_url}
